service: user-created-slack-alert

provider:
  name: aws
  runtime: nodejs10.x
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-offline

functions:
  user_created:
    handler: handler.user_created
    environment:
      webhookSecret: ${file(./secrets.${self:provider.stage}.json):webhookSecret}
      slackUrl: ${file(./secrets.${self:provider.stage}.json):slackUrl}
    events:
      - http:
          path: user_created
          method: post
